### ISSUE TITLE
Session resume is broken on the issues page

### ISSUE THREAD

**Issue by no-itsbackpack** [github/session-resume#8]
## Bug
- Create new Issue, enter Issue title and description
- Close tab and re-open using **Undo Close Tab**:
- The description gets repopulated but the title does not

## Solution
Removing `autocomplete` from the title input attribute seems to fix the bug, I figured I'd open an issue here so we can take a look at why the `autocomplete` attribute seems to be wiping the title field when a closed tab is re-opened

**Comment by thisis-Shitanshu** [comment]
Hey, I just recreated the bug in Chrome and Mozilla browser. And it's seems not only it is not repopulating the title in Mozilla but it's not repopulating either the body or title in Chrome. Would you like me work on it? as my first open source contribution??

**Comment by no-itsbackpack** [comment]
@thisis-Shitanshu thanks for recreating the problem in the other browsers 🙇, definitely think you should give it a shot ❤️❤️

**Comment by muan** [comment]
This doesn't seem to be caused by session-resume. 
Demo with just HTML: https://html-is.glitch.me/throwaway/autocomplete.html

![](https://cl.ly/3568e7d889da/Screen%252520Recording%2525202019-07-25%252520at%25252015.12.gif)
